name: Vinylspend
options:
  bundleIdPrefix: com.shimondeitel.vinylspend
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
  groupSortPosition: top
settings:
  base:
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.0"
    DEVELOPMENT_TEAM: "W7Q885Q59C"
    CODE_SIGN_STYLE: Automatic
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    TARGETED_DEVICE_FAMILY: "1"
    ENABLE_USER_SCRIPT_SANDBOXING: "YES"
targets:
  Vinylspend:
    type: application
    platform: iOS
    sources:
      - path: Vinylspend
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.vinylspend
        TARGETED_DEVICE_FAMILY: "1"
        INFOPLIST_FILE: Vinylspend/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: "YES"
        GENERATE_INFOPLIST_FILE: "NO"
  VinylspendTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: VinylspendTests
      - path: Vinylspend.storekit
    dependencies:
      - target: Vinylspend
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.vinylspend.tests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
  VinylspendUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: VinylspendUITests
    dependencies:
      - target: Vinylspend
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.vinylspend.uitests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
schemes:
  Vinylspend:
    build:
      targets:
        Vinylspend: all
        VinylspendTests: [test]
        VinylspendUITests: [test]
    run:
      config: Debug
      storeKitConfiguration: Vinylspend.storekit
    test:
      config: Debug
      storeKitConfiguration: Vinylspend.storekit
      targets:
        - VinylspendTests
        - VinylspendUITests
    archive:
      config: Release
